Update deployToAzure.yml

diff --git a/.github/workflows/deployToAzure.yml b/.github/workflows/deployToAzure.yml
--- a/.github/workflows/deployToAzure.yml
+++ b/.github/workflows/deployToAzure.yml
@@ -26,12 +26,27 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
+      # Install jq for JSON validation
+      - name: Install jq
+        run: sudo apt-get install -y jq
+
       # Create src/main/resources/credentials/jobhunter-service-account.json file from base64
       - name: Create jobhunter-service-account.json.json
         run: |
           echo "${{ secrets.GOOGLE_SERVICES_ANDROID }}" | base64 -di > src/main/resources/credentials/jobhunter-service-account.json
         shell: bash
-
+        
+      # Validate google-services.json
+      - name: Validate jobhunter-service-account.json.json
+        run: |
+          if [ -f src/main/resources/credentials/jobhunter-service-account.json ]; then
+            jq . src/main/resources/credentials/jobhunter-service-account.json > /dev/null || { echo "Invalid JSON in google-services.json"; cat src/main/resources/credentials/jobhunter-service-account.json; exit 1; }
+          else
+            echo "src/main/resources/credentials/jobhunter-service-account.json not found"
+            exit 1
+          fi
+        shell: bash
+        
       # Set up Docker Buildx
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
